server:
  port: 8080
  servlet:
    context-path: /api

spring:
  mvc:
    throw-exception-if-no-handler-found: true
    path-match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  profiles:
    group:
      "local": "console-logging"
      "dev": "file-logging,console-logging"
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  config:
    import: optional:file:.env[.properties]

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000

oauth:
  kakao:
    auth-url: ${KAKAO_OAUTH_URL}
    user-url: ${KAKAO_USER_URL}
    grant-type: "authorization_code"
    rest-api-key: ${KAKAO_REST_API_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET}

jwt:
  header: Authorization
  issuer: cupping_note
  client-secret: ${JWT_SECRET}
  refresh-token-expiry-seconds: 2592000 # 60초 * 60분 * 24시간 * 30일 = 1달
  access-token-expiry-seconds: 86400 # 60초 * 60분 * 24시간 = 1일