spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cupping_note;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2
      encoding: UTF-8
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
logging:
  level:
    root: info